export type WordEntry = { word:string; phonetic:string; meaning:string; example?:string; exampleSourceId?:number; exampleSourceUser?:string; pos?:string };
const make=(rows:string[][]):WordEntry[]=>rows.map(([word,phonetic,meaning,example])=>({word,phonetic,meaning,example}));

export const wordBanks:Record<string,WordEntry[]>={
  "CET-4":make([
    ["decline","/dɪˈklaɪn/","下降；拒绝","Sales began to decline in the winter."],
    ["indicate","/ˈɪndɪkeɪt/","表明；指示","The results indicate a steady improvement."],
    ["maintain","/meɪnˈteɪn/","维持；保养","It is important to maintain a healthy balance."],
    ["obtain","/əbˈteɪn/","获得","You must obtain permission before entering."],
    ["prevent","/prɪˈvent/","阻止；预防","Warm clothing can prevent heat loss."],
    ["require","/rɪˈkwaɪə/","需要；要求","This position will require excellent communication skills."],
    ["respond","/rɪˈspɒnd/","回应；反应","Please respond to the email by Friday."],
    ["variety","/vəˈraɪəti/","多样；种类","The market sells a variety of fresh fruit."],
  ]),
  "CET-6":make([
    ["accumulate","/əˈkjuːmjəleɪt/","积累","Small savings accumulate over time."],
    ["acknowledge","/əkˈnɒlɪdʒ/","承认；确认","The author must acknowledge all sources."],
    ["advocate","/ˈædvəkeɪt/","提倡；拥护","Many doctors advocate regular exercise."],
    ["allocate","/ˈæləkeɪt/","分配","The council will allocate funds to education."],
    ["ambiguous","/æmˈbɪɡjuəs/","模棱两可的","The instructions were ambiguous and confusing."],
    ["anticipate","/ænˈtɪsɪpeɪt/","预期；预料","We anticipate strong demand for the product."],
    ["arbitrary","/ˈɑːbɪtrəri/","任意的；武断的","The deadline seemed completely arbitrary."],
    ["coherent","/kəʊˈhɪərənt/","连贯的；条理清楚的","She presented a coherent argument."],
    ["confront","/kənˈfrʌnt/","面对；对抗","We must confront the problem directly."],
    ["controversial","/ˌkɒntrəˈvɜːʃl/","有争议的","The proposal remains highly controversial."],
    ["conventional","/kənˈvenʃənl/","传统的；常规的","They rejected the conventional approach."],
    ["distort","/dɪˈstɔːt/","歪曲；扭曲","Poor lighting can distort colours."],
    ["equivalent","/ɪˈkwɪvələnt/","相等的；等价物","One hour here is equivalent to two class periods."],
    ["facilitate","/fəˈsɪlɪteɪt/","促进；使便利","Technology can facilitate international cooperation."],
    ["fluctuate","/ˈflʌktʃueɪt/","波动","Energy prices fluctuate throughout the year."],
    ["implement","/ˈɪmplɪment/","实施","The company will implement the new policy next month."],
    ["inevitable","/ɪnˈevɪtəbl/","不可避免的","Some degree of change is inevitable."],
    ["integrate","/ˈɪntɪɡreɪt/","整合；融入","The course integrates theory with practice."],
    ["interpret","/ɪnˈtɜːprɪt/","解释；理解","Different readers may interpret the poem differently."],
    ["justify","/ˈdʒʌstɪfaɪ/","证明……合理","Can you justify the additional expense?"],
    ["manipulate","/məˈnɪpjəleɪt/","操纵；熟练操作","The software lets users manipulate images."],
    ["persistent","/pəˈsɪstənt/","坚持不懈的；持续的","Persistent effort eventually brought success."],
    ["preliminary","/prɪˈlɪmɪnəri/","初步的；预备的","Preliminary results look encouraging."],
    ["subsequent","/ˈsʌbsɪkwənt/","随后的","Subsequent research confirmed the finding."],
  ]),
  "IELTS":make([
    ["alleviate","/əˈliːvieɪt/","缓解","New measures may alleviate traffic congestion."],
    ["biodiversity","/ˌbaɪəʊdaɪˈvɜːsəti/","生物多样性","The forest supports remarkable biodiversity."],
    ["cohesive","/kəʊˈhiːsɪv/","有凝聚力的；连贯的","A cohesive essay is easier to follow."],
    ["compelling","/kəmˈpelɪŋ/","令人信服的","The researcher presented compelling evidence."],
    ["consecutive","/kənˈsekjətɪv/","连续的","Rain fell for five consecutive days."],
    ["conservation","/ˌkɒnsəˈveɪʃn/","保护；节约","Wildlife conservation requires global action."],
    ["deteriorate","/dɪˈtɪəriəreɪt/","恶化","Air quality may deteriorate during winter."],
    ["disparity","/dɪˈspærəti/","差距；不平等","The policy aims to reduce income disparity."],
    ["empirical","/ɪmˈpɪrɪkl/","实证的","The claim lacks empirical support."],
    ["enhance","/ɪnˈhɑːns/","提高；增强","Trees enhance the quality of urban life."],
    ["habitat","/ˈhæbɪtæt/","栖息地","Pollution threatens the animal's natural habitat."],
    ["infrastructure","/ˈɪnfrəstrʌktʃə/","基础设施","The region needs better transport infrastructure."],
    ["innovation","/ˌɪnəˈveɪʃn/","创新","Competition often encourages innovation."],
    ["mitigate","/ˈmɪtɪɡeɪt/","减轻；缓和","Green spaces help mitigate urban heat."],
    ["predominant","/prɪˈdɒmɪnənt/","占主导地位的","Tourism is the predominant local industry."],
    ["profound","/prəˈfaʊnd/","深远的；深刻的","Technology has had a profound social impact."],
    ["prohibit","/prəˈhɪbɪt/","禁止","The rules prohibit smoking indoors."],
    ["resilient","/rɪˈzɪliənt/","有韧性的；适应力强的","Children can be remarkably resilient."],
    ["scarce","/skeəs/","稀缺的","Clean water is scarce in the region."],
    ["sustainable","/səˈsteɪnəbl/","可持续的","We need a more sustainable energy system."],
    ["tangible","/ˈtændʒəbl/","明确的；有形的","The project produced tangible benefits."],
    ["urbanisation","/ˌɜːbənaɪˈzeɪʃn/","城市化","Rapid urbanisation creates housing pressure."],
    ["viable","/ˈvaɪəbl/","切实可行的","Solar power is becoming a viable alternative."],
    ["vulnerable","/ˈvʌlnərəbl/","脆弱的；易受伤害的","Coastal communities are vulnerable to storms."],
    ["widespread","/ˈwaɪdspred/","广泛的","The change received widespread public support."],
    ["offset","/ˈɒfset/","抵消","Lower fuel costs offset the higher rent."],
    ["prevalent","/ˈprevələnt/","普遍的；盛行的","The disease is more prevalent in crowded areas."],
    ["rehabilitate","/ˌriːəˈbɪlɪteɪt/","修复；使康复","The programme will rehabilitate damaged wetlands."],
  ]),
  "TOEFL":make([
    ["abundant","/əˈbʌndənt/","丰富的；充裕的","Fresh water was abundant in the valley."],
    ["adjacent","/əˈdʒeɪsnt/","相邻的","The laboratory is adjacent to the main library."],
    ["aggregate","/ˈæɡrɪɡət/","总计的；集合体","The aggregate data reveal a clear pattern."],
    ["analogous","/əˈnæləɡəs/","相似的；可类比的","The two biological processes are analogous."],
    ["autonomous","/ɔːˈtɒnəməs/","自治的；自主的","The region became largely autonomous."],
    ["chronological","/ˌkrɒnəˈlɒdʒɪkl/","按时间顺序的","The events are arranged in chronological order."],
    ["comprise","/kəmˈpraɪz/","包含；构成","Women comprise nearly half of the workforce."],
    ["concurrent","/kənˈkʌrənt/","同时发生的","The study tracked two concurrent changes."],
    ["deplete","/dɪˈpliːt/","耗尽","Intensive farming can deplete the soil."],
    ["disperse","/dɪˈspɜːs/","散布；驱散","Seeds disperse through wind and water."],
    ["erode","/ɪˈrəʊd/","侵蚀；削弱","Waves gradually erode the coastline."],
    ["explicit","/ɪkˈsplɪsɪt/","明确的；清楚的","The instructions contain an explicit warning."],
    ["indigenous","/ɪnˈdɪdʒənəs/","本土的；土著的","The museum celebrates indigenous culture."],
    ["inhibit","/ɪnˈhɪbɪt/","抑制；阻碍","Low temperatures inhibit plant growth."],
    ["intrinsic","/ɪnˈtrɪnsɪk/","固有的；内在的","Curiosity has intrinsic value in education."],
    ["nuance","/ˈnjuːɑːns/","细微差别","The translation misses an important nuance."],
    ["paradigm","/ˈpærədaɪm/","范式；典范","The discovery created a new scientific paradigm."],
    ["plausible","/ˈplɔːzəbl/","貌似合理的","The scientist offered a plausible explanation."],
    ["reinforce","/ˌriːɪnˈfɔːs/","加强；强化","The findings reinforce the earlier conclusion."],
    ["retain","/rɪˈteɪn/","保留；保持","Clay can retain water for long periods."],
    ["sediment","/ˈsedɪmənt/","沉积物","Layers of sediment formed beneath the lake."],
    ["simulate","/ˈsɪmjəleɪt/","模拟","The model can simulate climate change."],
    ["subordinate","/səˈbɔːdɪnət/","次要的；下级的","Economic goals were subordinate to safety."],
    ["synthesize","/ˈsɪnθəsaɪz/","综合；合成","The review will synthesize evidence from many studies."],
    ["tentative","/ˈtentətɪv/","暂定的；试探性的","Researchers reached a tentative conclusion."],
    ["terrestrial","/təˈrestriəl/","陆地的；地球的","The island supports many terrestrial species."],
    ["trigger","/ˈtrɪɡə/","引发；触发","A sudden temperature change can trigger migration."],
  ]),
};
